version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./results:/app/results
    environment:
      - PYTHONPATH=/app
    ports:
      - "8888:8888"
    stdin_open: true  # Garde stdin ouvert
    tty: true

  spark-master:
    image: bitnami/spark:3.5.1
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    

  spark-worker:
    image: bitnami/spark:3.5.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4g
    deploy:
      replicas: 2  # 2 workers
    depends_on:
      - spark-master
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    

volumes:
  data: